import React from "react";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { useRouter } from "next/router";

export default function Layout({ children, isLogin }) {
const router = useRouter();

  const logout = async (e) => {
    e.preventDefault();
    const user = await axios.get("/api/auth/logout").then((res)=>{
      router.replace("/login");
    });

  };

  return (
    <>
      <Head>
        <title>This is a test</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
        ////////////////////////////
        {/* <!-- Core CSS --> */}
        <link
          rel="stylesheet"
          href="/assets/vendor/css/core.css"
          className="template-customizer-core-css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendor/css/theme-default.css"
          className="template-customizer-theme-css"
        />
        <link rel="stylesheet" href="/assets/css/demo.css" />
        {/* <!-- Vendors CSS --> */}
        <link
          rel="stylesheet"
          href="/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"
        />
        {/* <!-- Page --> */}
        <link rel="stylesheet" href="/assets/vendor/css/pages/page-auth.css" />

        <script src="/assets/js/config.js"></script>
      </Head>

      {/* <!-- Layout wrapper --> */}
      {!isLogin ? (
        <div className="layout-wrapper layout-content-navbar">
          <div className="layout-container">
            {/* <!-- Menu --> */}

            <aside
              id="layout-menu"
              className="layout-menu menu-vertical menu bg-menu-theme"
            >
              <div className="app-brand demo">
                <a href="index.html" className="app-brand-link">
                  <span className="app-brand-logo demo"></span>
                  <span className="app-brand-text demo menu-text fw-bolder ms-2">
                    Dashboard
                  </span>
                </a>

                <a
                  href="#"
                  className="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none"
                >
                  <i className="bx bx-chevron-left bx-sm align-middle"></i>
                </a>
              </div>

              <div className="menu-inner-shadow"></div>

              <ul className="menu-inner py-1">
                {/* <!-- Dashboard --> */}
                <li className="menu-item active">
                  <Link href="/">
                    <a className="menu-link">
                      <i className="menu-icon tf-icons bx bx-home-circle"></i>
                      <div data-i18n="Analytics">Home</div>
                    </a>
                  </Link>
                </li>

                {/* <!-- Layouts --> */}
                <li className="menu-item ">
                  <Link href="/dashboard">
                    <a className="menu-link">
                      <i className="menu-icon tf-icons bx bx-layout"></i>
                      <div data-i18n="Layouts">Dashboard</div>
                    </a>
                  </Link>
                </li>
              </ul>
            </aside>
            {/* <!-- / Menu --> */}

            {/* <!-- Layout container --> */}
            <div className="layout-page">
              {/* <!-- Navbar --> */}

              <nav
                className="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                id="layout-navbar"
              >
                <div className="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                  <a className="nav-item nav-link px-0 me-xl-4" href="#">
                    <i className="bx bx-menu bx-sm"></i>
                  </a>
                </div>

                <div
                  className="navbar-nav-right d-flex align-items-center"
                  id="navbar-collapse"
                >
                  {/* <!-- Search --> */}
                  <div className="navbar-nav align-items-center">
                    <div className="nav-item d-flex align-items-center">
                      <i className="bx bx-search fs-4 lh-0"></i>
                      <input
                        type="text"
                        className="form-control border-0 shadow-none"
                        placeholder="Search..."
                        aria-label="Search..."
                      />
                    </div>
                  </div>
                  {/* <!-- /Search --> */}

                  <ul className="navbar-nav flex-row align-items-center ms-auto">
                    {/* <!-- User --> */}
                    <li className="nav-item navbar-dropdown dropdown-user dropdown">
                      <a
                        className="nav-link dropdown-toggle hide-arrow"
                        href="#"
                        data-bs-toggle="dropdown"
                      >
                        <div className="avatar avatar-online">
                          <img
                            src="../assets/img/avatars/1.png"
                            className="w-px-40 h-auto rounded-circle"
                          />
                        </div>
                      </a>
                      <ul className="dropdown-menu dropdown-menu-end">
                        <li>
                          <a className="dropdown-item" href="#">
                            <div className="d-flex">
                              <div className="flex-shrink-0 me-3">
                                <div className="avatar avatar-online">
                                  <img
                                    src="../assets/img/avatars/1.png"
                                    className="w-px-40 h-auto rounded-circle"
                                  />
                                </div>
                              </div>
                              <div className="flex-grow-1">
                                <span className="fw-semibold d-block">ADO</span>
                                <small className="text-muted">Admin</small>
                              </div>
                            </div>
                          </a>
                        </li>
                        <li>
                          <div className="dropdown-divider"></div>
                        </li>
                        <li>
                          <a className="dropdown-item" href="#">
                            <i className="bx bx-user me-2"></i>
                            <span className="align-middle">Mon Profile</span>
                          </a>
                        </li>
                        <li>
                          <div className="dropdown-divider"></div>
                        </li>
                        <li>
                          <a className="dropdown-item" href="#" onClick={(e)=>logout(e)}>
                            <i className="bx bx-power-off me-2"></i>
                            <span className="align-middle">Deconnexion</span>
                          </a>
                        </li>
                      </ul>
                    </li>
                    {/* <!--/ User --> */}
                  </ul>
                </div>
              </nav>

              {/* <!-- / Navbar --> */}

              {/* <!-- Content wrapper --> */}
              <div className="content-wrapper">
                {/* <!-- Content --> */}

                <div className="container-xxl flex-grow-1 container-p-y">
                  {/* <!-- Layout Demo --> */}
                  {children}
                  {/* <!--/ Layout Demo --> */}
                </div>
                {/* <!-- / Content --> */}

                {/* <!-- Footer --> */}
                <footer className="content-footer footer bg-footer-theme"></footer>
                {/* <!-- / Footer --> */}

                <div className="content-backdrop fade"></div>
              </div>
              {/* <!-- Content wrapper --> */}
            </div>
            {/* <!-- / Layout page --> */}
          </div>

          {/* <!-- Overlay --> */}
          <div className="layout-overlay layout-menu-toggle"></div>
        </div>
      ) : (
        <>{children}</>
      )}
      {/* <!-- / Layout wrapper --> */}
      {/* <!-- Core JS --> */}
      {/* <!-- build:js assets/vendor/js/core.js --> */}
      <script src="/assets/vendor/libs/jquery/jquery.js"></script>
      <script src="/assets/vendor/libs/popper/popper.js"></script>
      <script src="/assets/vendor/js/bootstrap.js"></script>
      <script src="/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

      <script src="/assets/vendor/js/menu.js"></script>
      {/* <!-- endbuild --> */}

      {/* <!-- Vendors JS --> */}

      {/* <!-- Main JS --> */}
      <script src="/assets/js/main.js"></script>
    </>
  );
}
